# Generated by Django 5.0.6 on 2024-07-06 05:05

from ast import In
from django.db import migrations

from ..models import WorkStyle, Interest

def create_initial_work_styles(apps, schema_editor):
    WorkStyle = apps.get_model("profiles", "WorkStyle")
    initial_work_styles = [
        '사기를 불어넣는',
        '도전적인',
        '개성이 뚜렷한',
        '결단력 있는',
        '공감능력이 좋은',
        '사교적인',
        '경청하는',
        '꼼꼼한',
        '리더십 있는',
        '계획적인',
        '열정적인',
        '눈치빠른',
        '완벽주의적인',
        '책임감 강한',
        '논리적인',
        '주관있는',
        '융통성 있는',
        '적응력 좋은',
        '현실적인',
        '협력적인',
        '통찰력 있는',
        '트렌드 빠른',
        '추진력 있는',
        '체계적인',
        '창의적인',
        '긍정적인',
    ]
    
    for work_style in initial_work_styles:
        WorkStyle.objects.create(name=work_style)
        
        
def create_initial_interests(apps, schema_editor):
    Interest = apps.get_model("profiles", "Interest")
    initial_interests = [
        '재무',
        '브랜딩',
        '마케팅',
        '기획/전략',
        '투자',
        '고객 서비스',
        '인사관리',
        '데이터',
        '인공지능',
        '운영관리',
        '교육',
        '헬스케어',
        '법률',
        '공공',
        '콘텐츠/미디어',
        '개발',
        '디자인',
        '회계',
    ]
    for interest in initial_interests:
        Interest.objects.create(name=interest)

class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_user_age"),
    ]

    operations = [
        migrations.RunPython(create_initial_work_styles),
        migrations.RunPython(create_initial_interests),
    ]
