# Generated by Django 5.0.6 on 2024-07-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_auto_20240706_0505"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="disc_character",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="gpt_summarized_personality",
            field=models.TextField(blank=True),
        ),
    ]
