# Generated by Django 5.0.6 on 2024-07-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_disc_character_user_gpt_summarized_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성'), ('N', '없음')], max_length=1),
        ),
    ]
