# Generated by Django 5.0.6 on 2024-07-11 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_shortquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_score', models.PositiveIntegerField()),
                ('i_score', models.PositiveIntegerField()),
                ('s_score', models.PositiveIntegerField()),
                ('c_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_from', to=settings.AUTH_USER_MODEL)),
                ('user_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_by', to=settings.AUTH_USER_MODEL)),
                ('work_styles', models.ManyToManyField(to='profiles.workstyle')),
                ('score', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.score')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='profiles.feedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.longquestion')),
            ],
        ),
    ]
