# Generated by Django 5.0.6 on 2024-07-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='long_questions',
            field=models.ManyToManyField(related_name='feedbacks', to='profiles.questionanswer'),
        ),
    ]
