# Generated by Django 5.0.6 on 2024-07-11 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_feedback_long_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='longquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='longquestion_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
