# Generated by Django 5.0.6 on 2024-07-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_longquestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='long_questions',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_answers',
            field=models.ManyToManyField(blank=True, related_name='feedbacks', to='profiles.questionanswer'),
        ),
    ]
