# Generated by Django 5.0.6 on 2024-07-17 12:47

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_feedback_long_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpt_summarized_personality',
            field=models.TextField(blank=True),
        ),
    ]

