# Generated by Django 5.0.6 on 2024-07-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_feedback_long_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DISCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_character', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('suitable_types', models.TextField()),
            ],
        ),
    ]
