# Generated by Django 5.0.6 on 2024-07-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_strength_suitabletype_weakness_discdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitabletype',
            name='with_name',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
