# Generated by Django 5.0.6 on 2024-07-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_suitabletype_with_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suitabletype',
            old_name='desciption',
            new_name='description',
        ),
    ]
