# Generated by Django 5.0.6 on 2024-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_rename_desciption_suitabletype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitabletype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='suitabletype',
            unique_together={('name', 'with_name')},
        ),
    ]
