# Generated by Django 5.0.6 on 2024-07-17 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_user_gpt_summarized_personality"),
        ("profiles", "0015_alter_suitabletype_name_and_more"),
    ]

    operations = []
