# Generated by Django 5.0.6 on 2024-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_merge_20240717_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpt_summarized_personality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
