# Generated by Django 5.0.6 on 2024-07-20 11:47

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_profileimage_user_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to=profiles.models.PathAndRename('profile-images/')),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_image_object', to=settings.AUTH_USER_MODEL),
        ),
    ]
