# Generated by Django 5.0.6 on 2024-07-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_profileimage_image_alter_profileimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discdata',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='discdata',
            name='suitable_type',
        ),
        migrations.RemoveField(
            model_name='discdata',
            name='weakness',
        ),
        migrations.AlterUniqueTogether(
            name='suitabletype',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Strength',
        ),
        migrations.DeleteModel(
            name='SuitableType',
        ),
        migrations.DeleteModel(
            name='DISCData',
        ),
        migrations.DeleteModel(
            name='Weakness',
        ),
    ]
