# Generated by Django 5.0.6 on 2024-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback_style',
            field=models.CharField(choices=[('hard', '솔직한 피드백'), ('soft', '배려있는 피드백')], default='hard', max_length=10),
            preserve_default=False,
        ),
    ]
