# Generated by Django 5.0.6 on 2024-08-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_user_feedback_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpt_summarized_personality',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
