# Generated by Django 5.0.6 on 2024-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_user_gpt_summarized_personality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpt_summarized_personality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
