# Generated by Django 5.0.6 on 2024-08-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
