# Generated by Django 5.0.6 on 2024-08-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_user_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='domain',
        ),
    ]
