# Generated by Django 5.0.6 on 2024-08-24 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_remove_user_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='last_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
