# Generated by Django 5.0.6 on 2024-08-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_feedback_last_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
